/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package span.digital.backend.challenge;

import static org.junit.jupiter.api.Assertions.assertEquals;

import java.io.File;
import java.io.FileNotFoundException;
import java.net.URL;
import java.util.List;
import java.util.Map;
import java.util.Set;

import org.junit.jupiter.api.Test;


public class AppTest {
    
    @Test
    public void testMain_expectedLeagueResults() {
        
        //Given
        File testFile;
        try {
            URL url = this.getClass().getResource("/matches.txt");
            if (url == null) {
                throw new FileNotFoundException();
            }
            testFile = new File(url.getFile());
        } catch (FileNotFoundException e) {
            throw new RuntimeException(e.getMessage());
        }
        
        //When
        List<Set<Team>> matchList = MatchListInputFileProcessor.getMatchList(testFile);
        Map<String, Integer> league = LeagueGenerator.generateLeague(matchList);
        
        //Then
        assertEquals(league.get("Tarantulas").intValue(), 6);
        assertEquals(league.get("Lions").intValue(), 5);
        assertEquals(league.get("FC Awesome").intValue(), 1);
        assertEquals(league.get("Snakes").intValue(), 1);
        assertEquals(league.get("Grouches").intValue(), 0);
    }
}
